#!/bin/bash

function usage()
{
  cat << EOF
  usage: $0 options

  Gebruik dit script om een rman commando uit te voeren op alle draaiende instances.

  OPTIONS:
     -h         toont dit helpscherm
     -DB        De SID van de Databases   (komma gescheiden, default alle draaiende instances)
     -script    gebruik de inhoud van het meegegeven script als basis voor RMAN.
     -x         debug mode                (default uit)

     Overige opties worden gezien als de query.
     Let op: er kan er 1 gegeven worden. Alleen de laatste wordt gebruikt.
EOF
  exit 0

}

if [ $(whoami) != 'oracle' ]; then
  sudo -u oracle "$0" $@
  exit
fi

while [ -n "$1" ]; do
case $1 in
  -h) usage; exit 0 ;;
  -DB) export DBs=$2 ; shift 2 ;;
  -script) QRY=$(cat "$2") ; shift 2 ;;
  -x) set -vx ; shift 1 ;;
  *) QRY=$1 ; shift 1 ;;
esac
done

if [ ! -f /etc/oratab ]; then
  echo "/etc/oratab does not exist. Probably not an Oracle server."
  exit 1
fi

. /stage/oracle/scripts/bash/oralib > /dev/null

[ "$DBs" ] && DBs=$(echo "$DBs" | sed 's/,/ /') || DBs=$(running_instances|sort)

for inst in $DBs
  do
  run_rman $inst "$QRY" | sed '/^$/d;s/^/'$inst' /'
  done
